###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /project
        volumes:
            - '.:/project'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=yagodin_d_qschool_DB
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        ports:
            - '5002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /project
        volumes:
            - '.:/project'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '5000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /project
        volumes:
            - '.:/project'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
